services:
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  web :
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env  
    depends_on:
      - redis
    # override the default CMD if needed
    # command: sh -c "gunicorn api.index:app --bind 0.0.0.0:8080 --workers 5 --threads 4 --timeout 120"

