services:
  - type: web
    name: ruthenium-web

    dockerBuild:
      dockerfilePath: Dockerfile
      context: .

    port: 8080

    plan: free
    autoDeploy: true

    envVars:
      - key: FLASK_SECRET
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: CALLBACK_URI
        sync: false
      - key: REDIS_URL
        sync: false